### ISSUE TITLE
Regular updates

### ISSUE THREAD

**Issue by dannystaple** [flemay/docker-images#2]
This image and it's components have not been updated in 2 years. This may be troublesome for container images built on newer OCI systems. It may also be troublesome from a security POV.

Perhaps a dependabot and automatic image build process could improve this?

**Comment by flemay** [comment]
Hi @dannystaple , `flemay/musketeers` hasn't been updated in 1 year. They generally get updated automatically using GitHub Actions but for some reason, they have been failing. I need to fix the pipelines.

**Comment by flemay** [comment]
I have fixed the pipelines! A new version of `flemay/mustkeers` has been deployed, and it should get updated every month. Thank you for reaching out!
